(in-package "ACL2")

;; (include-book "config")
;; (include-book "helper")
;; (include-book "SMT-extract")
;; (include-book "SMT-formula")
;; (include-book "SMT-function")
;; (include-book "SMT-translator")
;; (include-book "SMT-interpreter")
;; (include-book "SMT-run")
;; (include-book "SMT-z3")
(include-book "SMT-connect")
