(defun fake-z3 (term)
  (cond ((car 'proved) (1 "proved"))
	((car 'counterexample) (2 "counterexample" "[x = 1, y = 2]"))
	((car 'syntax-error) (3 "SyntaxError: What do you mean by ..."))
	((car 'timeout) (4 "Running out of time, program got terminated..."))
	(t nil)))

(defun my-prove (term hint)
  (cond (()
	 (prog2$ (cw "first is equal ~q0" term)
		 (if (equal (car term) 'equal))))
	()))
